
<br><br><center><h4 style="font-weight: bold;"> HOME </h4></center><br>
<a href="Add-Procedure-QA.php" class="btn btn-primary" style=" margin-top:20px; margin-left:1060px; font-family:'Sofia Pro', sans-serif;">Add To Home</a><br><br>
<center>
<table class="table" style="background-color: #7a7a7a63;font-family:'Sofia Pro', sans-serif; border: 1px solid black;">
  <thead>
    <tr>
        <td>
        IMDS(International Material Data System)
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
    <tr>
        <td>
        Be Standard System (NORMES FCA)
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
    <tr>
        <td>
        RIDBUL (FCA Standard Components Catalogue)
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
    <tr>
        <td>
        Yazaki Web Mail
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
    <tr>
        <td>
        BCD
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
    <tr>
        <td>
        Gestion Equimenents IT
        </td>
        <td>
        <button type="button" class="btn btn-dark">Enter</button>
        <a href="" class="btn" style="background-color:#f94a00; color:white;"><i class="bi bi-pencil-square"></i></a>
        <a href="" class="btn" style="background-color:#f30000; color:white;"><i class="bi bi-trash"></i></a>
        </td>
    </tr>
</table>
  </center>


