<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title><?= $pageTitle  ?></title>
  <meta content="" name="description">
  <meta name="keywords" content="au theme template">

   <!-- Favicons -->
   <link rel="icon" type="image/x-icon" href="./assets/img/yazaki.jpg">

  <!-- Sofia Pro -->
  <link href="http://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet">
  
<!-- Bootstrap CSS-->
<link href="./vendor/bootstrap/bootstrap.min.css" rel="stylesheet" media="all">

<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  
  <!-- Template Main CSS File -->
  <link href="./assets/css/style1.css" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
      <div class="container d-flex align-items-center justify-content-between">

          <div class="logo" style="margin-left: -50px; width:400px;">
            <a href="index-manager.php"><img src="assets/img/yazaki.png" alt="" class="img-fluid"></a>
          </div>
          
        <nav id="navbar" class="navbar" style="margin-left:50px;">
            <ul>
              <li><a class="nav-link <?php if($page=='home'){ echo 'active';} ?>" href="./index-manager.php">HOME</a></li>
              <li class="dropdown"><a href="#" class="nav-link <?php if($page=='IT'){ echo 'active';} ?>" style="text-decoration: none;">IT<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                    <ul>
                    <li><a href="#">IT Procedures </a></li>
                    <li><a href="#">IT Form</a></li>
                    <li><a href="#">Web Mail</a></li>
                    <li><a href="#">Phone</a></li>
                    </ul>
              </li>

              <li class="dropdown"><a href="#"style="text-decoration: none;" class="nav-link <?php if($page=='Procedure-QA'  || $page=='Instructions-QA' || $page=='Politique' || $page=='YAPT Controle Plan' || $page=='Manual Qualité'){ echo 'active';} ?>">QUALITY<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                    <ul>
                    <li><a href="Instructions-QA.php" class="nav-link <?php if($page=='Instructions-QA'){ echo 'active';} ?>">Quality instructions</a></li>
                    <li class="dropdown"><a href="#" class="nav-link <?php if($page=='Procedure-QA' ||  $page=='Cutting-QA'){ echo 'active';} ?>">Quality Procedures<i class="fa fa-chevron-right"></i></a>
                        <ul style="margin-left:52px;">
                        <li><a href="#" class="">Cutting Procedures</a></li>
                        <li><a href="./Procedure-QA.php" class="nav-link <?php if($page=='Procedure-QA'){ echo 'active';} ?>">Global Quality Strandard</a></li>
                        </ul>
                    </li>
                    <li><a href="" class="<?php if($page=='Politique'){ echo 'active';} ?>">Policy / Mission and Vision <br> Quality & IATF 16949 Certificate</a></li>
                    <li><a href="" class="<?php if($page=='YAPT Controle Plan'){ echo 'active';} ?>">YAPT Controle Plan</a></li>
                    <li><a href="#" class="<?php if($page=='Manuel Qualité'){ echo 'active';} ?>">Quality Manual</a></li>
                    </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">RH<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                  <li><a href="#">RH Procedure </a></li>
                  <li><a href="#">RH Instruction </a></li>
                  <li><a href="#">RH Manual </a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">Finance<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                <li><a href="#">Finance Procedures </a></li>
                <li><a href="#">Finance Instructions </a></li>
                <li><a href="#">Finance Manual </a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">LOGISTIC<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                <li><a href="#">LOGISTIC Procedures </a></li>
                <li><a href="#">LOGISTIC Instructions </a></li>
                <li><a href="#">LOGISTIC Manual </a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">PLPP/ENG<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                <li><a href="#">PLPP/ENG Procedures </a></li>
                <li><a href="#">PLPP/ENG Instructions </a></li>
                <li><a href="#">PLPP Manual </a></li>
                </ul>
              </li>
              <li><a class="dropdown" style="text-decoration: none;" href="#hero">PRODUCTION</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
         </nav><!-- .navbar -->
         &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          <div class="dropdown text-end" style="margin-right:-50px;">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img  src="./Dashboard/uploads/<?= $_SESSION['avatar_manager'] ?>" alt="mdo" width="32" height="32" class="rounded-circle">
              </a> 
              <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><h6><a class="dropdown-item" href="#"><?= $_SESSION['manager_name'] ?></a></h6></li>
                <li><a class="dropdown-item" href="#"><?= $_SESSION['email_manager'] ?></a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="./logout-manager.php">Logout</a></li>
              </ul>
            </div>
              <div class="b-example-divider"></div>
    </div>
  </header>
  <br>
      <section id="hero" style="margin-top: 50px;">
            <!-- Partie dynamique  -->
            <?php include $template . '.phtml'; ?>
            <!-- Partie dynamique  -->
          
      </section>
       <!-- Vendor JS Files -->
  <script src="assets/vendor/aos/aos.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>