
<!-- Login Form -->

<form class="login100-form validate-form" method="POST" action="<?php $_SERVER['PHP_SELF'] ?>" style="height:440px;">
<span class="login100-form-title p-b-48">
<img style="margin-top:5px;" src="https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/64/000000/external-user-interface-kiranshastry-lineal-kiranshastry-1.png"/>
</span>

<span class="login100-form-title p-b-26" >
	User Login
</span>

<?php if (count($errors1) > 0) : ?>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">

			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<?= $errors1[0] ?> 
	</div>
<?php endif; ?>

<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
	<input class="input100" type="text" name="email_user" required>
	<span class="focus-input100" data-placeholder="Email"></span>
</div>

<div class="wrap-input100 validate-input" data-validate="Enter password" required  >
	<span class="btn-show-pass">
		<i class="zmdi zmdi-eye-off"></i>
	</span>
	<input class="input100" type="password" name="password_user">
	<span class="focus-input100" data-placeholder="Password"></span>
</div>

<div class="container-login100-form-btn">
	<div class="wrap-login100-form-btn">
		<div class="login100-form-bgbtn"></div>
		<input value="Login" type="submit" class="login100-form-btn" name="submit1" style="cursor: pointer;">
	</div>
</div>
</form>



<div id="dropDownSelect1"></div>
	
