
<div class="main-content" style="margin-top:-30px;">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
        <h2 class="title-1 m-b-25" style="color:black; font-weight:bold;margin-top:-50px"><center>Admins List</center> </h2>
            <a href="./Add-admin.php" class="au-btn au-btn-icon au-btn--blue" style="color:white;margin-left:395px; width:170px; font-size:15px;">
                    <i class="zmdi zmdi-plus"></i>add Admin</a> <br> <br>
                    </a>  
                    <table class="table table-dark table-hover" style="margin-left:0px;">
                    <thead>
                        <tr>
                        <th scope="col">id</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Password</th>
                        <th scope="col">Contact</th>
                        <th scope="col">Image</th>
                        <th scope="col">Actions</th>
                        </tr>
                    </thead>
                <tbody>
                <?php foreach ($admins as $admin) : ?>
                    <tr>
                    <th scope="row"><?= $admin['id'] ?></th>
                    <td><?= $admin['admin_name'] ?></td>
                    <td><?= $admin['email'] ?></td>
                    <td><?= $admin['password'] ?></td>
                    <td><?= $admin['Tel'] ?></td>
                    <td ><img src="uploads/<?= $admin['avatar'] ?>" style="width:70px;height:70px;"></td>
                    <td>
                    <a href="Edit-admin.php?id=<?= $admin['id'] ?>" class="btn" style="background-color:#f94a00; color:white;"><i class="fas fa-edit"></i></a>
          <!-- Button trigger modal -->
            <a href="delete-admin.php?id=<?= $admin['id'] ?>" class="btn" style="background-color:#f30000; color:white;"><i class="fas fa-trash"></i></a>
                    <!-- Modal -->
            
                </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            </table>

            
        </div>
        
    </div>
    
</div>
                              
  