
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title><?= $pageTitle ?></title>

   <!-- Favicons -->
   <link rel="icon" type="image/x-icon" href="../assets/img/yazaki.jpg">

    <!-- Fontfaces CSS-->
    <link href="css/font-face.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Sofia Pro -->
    <link href="http://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet">

    <!-- Bootstrap CSS-->
    <link href="vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Vendor CSS-->
    <link href="vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/theme.css" rel="stylesheet" media="all">
    <link href="css/all.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
   
<div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none" >
            <div class="header-mobile__bar" >
                <div class="container-fluid" >
                    <div class="header-mobile-inner">
                    <a class="logo" href="index.html">
                            <img src="images/logo.png" alt="YAZAKI" />
                        </a>
                        <button class="hamburger hamburger--slider" type="button" >
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid"></div>
                    <ul class="navbar-mobile__list list-unstyled">
                    <li class="<?php if($page=='Dashboard'){ echo 'active';} ?> has-sub">
                            <a class="js-arrow" href="./index.php">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#" >
                            <i class="fas fa-user-shield"></i>Admins</a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li class="<?php if($page=='Add-admin'){ echo 'active';} ?>">
                                <a href="./Add-admin.php">
                                <i class="fas fa-plus"></i>Add Admin
                                </a>
                                </li>
                                <li class="<?php if($page=='Admins-list' || $page=='Edit-admin'){ echo 'active';} ?>">
                                    <a href="./Admins-list.php">
                                    <i class="fas fa-clipboard-list"></i>Admins List
                                </a>
                                </li>
                            </ul>
                        </li>
                        <li class="<?php if($page=='Add-Manager'){ echo 'active';} ?> has-sub">
                            <a class="js-arrow" href="#">
                            <i class="fas fa-users-cog"></i>Managers</a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li class="<?php if($page=='Add-Manager'){ echo 'active';} ?>">
                                    <a href="./Add-manager.php">
                                    <i class="fas fa-plus"></i> Add Manager
                                    </a>
                                </li>
                                <li class="<?php if($page=='Managers-list' || $page=='Edit-manager'){ echo 'active';} ?>">
                                    <a href="./Managers-list.php">
                                    <i class="fas fa-clipboard-list"></i>Managers List
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->

        
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block" >
            <div class="logo">
                <a href="./index.php">
                    <img src="images/logo1.png" alt="YAZAKI" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                    <li class="<?php if($page=='Dashboard'){ echo 'active';} ?> has-sub">
                            <a class="js-arrow" href="./index.php">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                            <i class="fas fa-user-shield"></i>Admins</a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li class="<?php if($page=='Add-admin'){ echo 'active';} ?>">
                                <a href="./Add-admin.php">
                                <i class="fas fa-plus"></i>Add Admin
                                </a>
                                </li>
                                <li class="<?php if($page=='Admins-list' || $page=='Edit-admin'){ echo 'active';} ?>">
                                    <a href="./Admins-list.php">
                                    <i class="fas fa-clipboard-list"></i>Admins List
                                </a>
                                </li>
                                <li hidden class="<?php if($page=='Edit-admin'){ echo 'active';} ?>">
                                    <a href="./Edit-admin.php">
                                    <i class="fas fa-clipboard-list"></i>Edit admin
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                            <i class="fas fa-users-cog"></i>Managers</a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li class="<?php if($page=='Add-Manager'){ echo 'active';} ?>">
                                    <a href="./Add-manager.php">
                                    <i class="fas fa-plus"></i> Add Manager
                                    </a>
                                </li>
                                <li class="<?php if($page=='Managers-list' || $page=='Edit-manager'){ echo 'active';} ?>">
                                    <a href="./Managers-list.php">
                                    <i class="fas fa-clipboard-list"></i>Managers List
                                    </a>
                                </li>
                                <li hidden class="<?php if($page=='Edit-manager'){ echo 'active';} ?>">
                                    <a href="./Edit-manager.php">
                                    <i class="fas fa-clipboard-list"></i>Edit manager
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                            <i class="fas fa-users"></i>Users</a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li class="<?php if($page=='Add-User'){ echo 'active';} ?>">
                                    <a href="./Add-user.php">
                                    <i class="fas fa-plus"></i> Add User
                                    </a>
                                </li>
                                <li class="<?php if($page=='Users-list' || $page=='Edit-user'){ echo 'active';} ?>">
                                    <a href="./Users-list.php">
                                    <i class="fas fa-clipboard-list"></i>Users List
                                    </a>
                                </li>
                                <li hidden class="<?php if($page=='Edit-user'){ echo 'active';} ?>">
                                    <a href="./Edit-user.php">
                                    <i class="fas fa-clipboard-list"></i>Edit user
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container" >
            <!-- HEADER DESKTOP-->
            <header class="header-desktop" >
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="search.php" method="POST">
                                <input class="au-input au-input--xl" type="text" name="search" placeholder="Search for datas &amp; reports..." />
                                <select name="search_type" class="au-btn--submit" style="color:white;"> 
                                    <option value="0">Name</option>
                                    <option value="1">Email</option>
                                    <option value="2">Phone</option>
                                </select>
                                <button class="au-btn--submit" type="submit">
                                    <i class="zmdi zmdi-search"></i>
                                </button>
                            </form>
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="./uploads/<?= $_SESSION['avatar'] ?>" alt="John Doe" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#"><?= $_SESSION['admin_name'] ?> </a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="./uploads/<?= $_SESSION['avatar'] ?>" alt="John Doe"/>
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#"><?= $_SESSION['admin_name'] ?></a>
                                                    </h5>
                                                    <span class="email"><?= $_SESSION['email'] ?></span>
                                                </div>
                                            </div>
                                                <div class="account-dropdown__item">
                                                    <a href="Account.php">
                                                    <i class="fas fa-user-circle"></i>Account</a>
                                                </div>
                                            <div class="account-dropdown__footer">
                                                <a href="../logout-admin.php">
                                                <i class="fas fa-sign-out-alt"></i>Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- END HEADER DESKTOP -->
            <section id="hero" style=" margin-top: 50px;">

            <?php include $template . '.phtml'; ?>

            </section>
             <!-- END PAGE CONTAINER-->
     </div>

</div>
<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
<!-- Jquery JS-->
<script src="vendor/jquery-3.2.1.min.js"></script>
<!-- Bootstrap JS-->
<script src="vendor/bootstrap-4.1/popper.min.js"></script>
<script src="vendor/bootstrap-4.1/bootstrap.min.js"></script>
<!-- Vendor JS       -->
<script src="vendor/slick/slick.min.js">
</script>
<script src="vendor/wow/wow.min.js"></script>
<script src="vendor/animsition/animsition.min.js"></script>
<script src="vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
</script>
<script src="vendor/counter-up/jquery.waypoints.min.js"></script>
<script src="vendor/counter-up/jquery.counterup.min.js">
</script>
<script src="vendor/circle-progress/circle-progress.min.js"></script>
<script src="vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="vendor/chartjs/Chart.bundle.min.js"></script>
<script src="vendor/select2/select2.min.js">
</script>

<!-- Main JS-->
<script src="js/main.js"></script>

</body>

</html>
<!-- end document-->
