<div class="main-content" style="margin-top:-20px;">
    <div class="section__content section__content--p30" >
        <div class="container-fluid">
            <h2 class="title-1 m-b-25" style="color:black; font-weight:bold;margin-top:-50px"><center>users List</center> </h2>
              <center><a  href="./Add-user.php" class="au-btn au-btn-icon au-btn--blue" style=""><i class="zmdi zmdi-plus"></i>add user</a></center> <br>
                <table class="table table-dark table-hover">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Full Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Password</th>
                            <th scope="col">Department</th>
                            <th scope="col">Contact</th>
                            <th scope="col">Avatar</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <th scope="row"><?= $user['id_user'] ?></th>
                            <td><?= $user['user_name'] ?></td>
                            <td><?= $user['email_user'] ?></td>
                            <td><?= $user['password_user'] ?></td>
                            <td><?= $user['department'] ?></td>
                            <td><?= $user['Tel_user'] ?></td>
                            <td><img src="./uploads/<?= $user['avatar_user'] ?>" alt=""></td>
                            <td>
                                    <a href="./Edit-user.php?id=<?= $user['id_user'] ?>"  class="btn" style="background-color:#f94a00; color:white;"><i class="fas fa-edit"></i></a>
                                    <a href="./delete-user.php?id=<?= $user['id_user'] ?>"  class="btn" style="background-color:#f30000; color:white;"><i class="fas fa-trash"></i></a>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" style="color:white;" data-bs-toggle="modal" data-bs-target="#deleteuser<?= $user['id_user'] ?>"><i class="fas fa-trash"></i></button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="deleteuser<?= $user['id_user'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete user </h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                            Do you want to delete <?= $user['user_name'] ?> ?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button>
                                                <a href="delete_todo.php?id=<?= $user['id_user'] ?>" type="button" class="btn btn-danger">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
        </div>
    </div>
</div>
