<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title><?= $pageTitle ?></title>
  <meta content="" name="description">
  <meta content="" name="keywords">

   <!-- Favicons -->
   <link rel="icon" type="image/x-icon" href="../assets/img/yazaki.jpg">

<!-- Sofia Pro -->
<link href="http://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet">
  
<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Vendor CSS Files -->
  <link href="../assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="../assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="../assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="../assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="css2/user.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Ninestars - v4.7.0
  * Template URL: https://bootstrapmade.com/ninestars-free-bootstrap-3-theme-for-creative/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>
  <!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
      <div class="container d-flex align-items-center justify-content-between">

          <div class="logo" style="margin-left: -80px; width:400px;">
            <a href="index-admin.php"><img src="../assets/img/yazaki.png" alt="" class="img-fluid"></a>
          </div>
          
        <nav id="navbar" class="navbar" style="margin-left:150px;">
            <ul>
              <li><a class="nav-link <?php if($page=='Home'){ echo 'active';} ?>" href="home-user.php">HOME</a></li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">IT<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                    <ul>
                    <li><a href="#">Drop Down 1</a></li>
                    <li><a href="#">Drop Down 2</a></li>
                    <li><a href="#">Drop Down 3</a></li>
                    <li><a href="#">Drop Down 4</a></li>
                    </ul>
             </li>

              <li class="dropdown <?php if($page=='Procedure QA YAPT' || $page=='Instruction Qualité' || $page=='Politique' || $page=='YAPT Controle Plan' || $page=='Manuel Qualité'){ echo 'active';} ?>"><a href="#"style="text-decoration: none;" class="">QUALITY<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                    <ul>
                    <li><a href="Procedures-qa.php" class="<?php if($page=='Procedure QA YAPT'){ echo 'active';} ?>">Procedure Qualité</a></li>
                    <li class="dropdown"><a href="#" class="<?php if($page=='Instruction Qualité'){ echo 'active';} ?>">Instruction Qualité<i class="fa fa-chevron-right"></i></a>
                        <ul style="margin-left:52px;">
                        <li><a href="#" class="">Drop Down 3</a></li>
                        <li><a href="#" class="">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a href="#" class="<?php if($page=='Politique'){ echo 'active';} ?>">Politique / Mission et Vision <br> qualité & Certificat IATF 16949</a></li>
                    <li><a href="#" class="<?php if($page=='YAPT Controle Plan'){ echo 'active';} ?>">YAPT Controle Plan</a></li>
                    <li><a href="#" class="<?php if($page=='Manuel Qualité'){ echo 'active';} ?>">Manuel Qualité</a></li>
                    </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">RH<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                  <li><a href="#">Drop Down 1</a></li>
                  <li><a href="#">Drop Down 2</a></li>
                  <li><a href="#">Drop Down 3</a></li>
                  <li><a href="#">Drop Down 4</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">FINANCE<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                  <li><a href="#">Drop Down 1</a></li>
                  <li><a href="#">Drop Down 2</a></li>
                  <li><a href="#">Drop Down 3</a></li>
                  <li><a href="#">Drop Down 4</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">LOGISTIC<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                  <li><a href="#">Drop Down 1</a></li>
                  <li><a href="#">Drop Down 2</a></li>
                  <li><a href="#">Drop Down 3</a></li>
                  <li><a href="#">Drop Down 4</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#" style="text-decoration: none;">PLPP/ENG<i class="fa fa-chevron-down" style="font-size:14px"></i></a>
                <ul>
                  <li><a href="#">Drop Down 1</a></li>
                  <li><a href="#">Drop Down 2</a></li>
                  <li><a href="#">Drop Down 3</a></li>
                  <li><a href="#">Drop Down 4</a></li>
                </ul>
              </li>
              <li><a class="dropdown" style="text-decoration: none;" href="#hero">PRODUCTION</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
         </nav><!--  end navbar -->
              <div class="b-example-divider"></div>
    </div>
  </header>



      <!-- Vendor JS Files -->
      <script src="../assets/vendor/aos/aos.js"></script>
  <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="../assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="../assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="../assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="../assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="../assets/js/main.js"></script>

</body>

</html>   

 